Repository bsdci/libioc, pull requests merged in 2019-01, with the labels that each got.

#597 Release v0.4.0
  setup.py
Labels: chore

#600 FreeBSD Release download of lib32.txz release asset
  ioc/Release.py
Labels: bug

#603 get unprefixed BridgeInterface name by accessing the name attribute
  ioc/Network.py
Labels: bug

#608 Fix filtering templates
  ioc/Config/Jail/BaseConfig.py
Labels: bug

#612 JailConfig parameter vnet must be boolean
  libioc/Config/Jail/BaseConfig.py
Labels: enhancement

#615 Fix pkg install and freebsd update
  libioc/Pkg.py
  libioc/ResourceUpdater.py
Labels: bug

#616 handle config property None-values as such
  libioc/Config/Jail/BaseConfig.py
  libioc/helpers.py
Labels: bug

#619 catch TypeError instead of ValueError when parsing input for none values
  libioc/Config/Jail/BaseConfig.py
Labels: bug

#620 rename IOCAGE_* env variables to IOC_*
  libioc/Firewall.py
  libioc/Jail.py
  libioc/Network.py
  libioc/ZFSShareStorage.py
Labels: chore
